/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ApiPublicPosterRouteImport } from './routes/api/public/poster'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPosterRoute = ApiPublicPosterRouteImport.update({
  id: '/api/public/poster',
  path: '/api/public/poster',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/resume': typeof ResumeRoute
  '/reviews': typeof ReviewsRoute
  '/thank-you': typeof ThankYouRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/poster': typeof ApiPublicPosterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/resume': typeof ResumeRoute
  '/reviews': typeof ReviewsRoute
  '/thank-you': typeof ThankYouRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/poster': typeof ApiPublicPosterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/resume': typeof ResumeRoute
  '/reviews': typeof ReviewsRoute
  '/thank-you': typeof ThankYouRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/poster': typeof ApiPublicPosterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime'
    | '/resume'
    | '/reviews'
    | '/thank-you'
    | '/api/chat'
    | '/projects/$slug'
    | '/api/public/poster'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anime'
    | '/resume'
    | '/reviews'
    | '/thank-you'
    | '/api/chat'
    | '/projects/$slug'
    | '/api/public/poster'
  id:
    | '__root__'
    | '/'
    | '/anime'
    | '/resume'
    | '/reviews'
    | '/thank-you'
    | '/api/chat'
    | '/projects/$slug'
    | '/api/public/poster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeRoute: typeof AnimeRoute
  ResumeRoute: typeof ResumeRoute
  ReviewsRoute: typeof ReviewsRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiChatRoute: typeof ApiChatRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ApiPublicPosterRoute: typeof ApiPublicPosterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poster': {
      id: '/api/public/poster'
      path: '/api/public/poster'
      fullPath: '/api/public/poster'
      preLoaderRoute: typeof ApiPublicPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeRoute: AnimeRoute,
  ResumeRoute: ResumeRoute,
  ReviewsRoute: ReviewsRoute,
  ThankYouRoute: ThankYouRoute,
  ApiChatRoute: ApiChatRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ApiPublicPosterRoute: ApiPublicPosterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
